---
title: "Ex4"
author: "Lia Baumann"
date: '2022-05-13'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
library(readr)        
library(dplyr)        
library(ggplot2)      
library(lubridate)
```

## Task 1

```{r function pre-task}
testfun <- function(){}
testfun()
class(testfun)
testfun <- function(etwas){
  print(etwas)
}
testfun(etwas="chli meh und doch nüt")
my_age <- function(birthday,units){
  difftime(Sys.time(),birthday,units=units)
}
my_age(birthday="1992-07-02",units="days")
my_age("1992-07-02","days")
my_age <- function(birthday,units="days"){
  difftime(Sys.time(),birthday,units=units)
}
my_age("1992-07-02","hours")
```
```{r function Task 1}
euclid_dist <- function(x,y){
  sqrt((x-lead(x,1))^2+(y-lead(y,1))^2)
} #x=E, y=N
euclid_dist(c(4,6,8),c(5,1,3))

sqrt((c(4,6,8)-lead(c(4,6,8),1))^2+(c(5,1,3)-lead(c(5,1,3),1))^2) #Test looks reasonable
```
```{r Task2}
wildschwein_BE_2056 <- read_delim("wildschwein_BE_2056.csv")
wildschwein_BE_filtered <- wildschwein_BE_2056 %>%
  filter(DatetimeUTC <= "2015-04-15" & DatetimeUTC > "2015-04-01") %>% #incredibly annoying, values before 01.04. are inside the filter...
  filter(TierName == "Rosa" | TierName == "Sabi")
```
```{r Task3}
wildschwein_BE_filtered <- wildschwein_BE_filtered %>%
  mutate(roundToQuarterHour = round_date(DatetimeUTC,"15 mins"))
```
```{r Task4}
wildschwein_Sabi <- wildschwein_BE_filtered %>%
  filter(TierName =="Sabi") %>%
  as.data.frame()
str(wildschwein_Sabi)
wildschwein_Rosa <- wildschwein_BE_filtered %>%
  filter(TierName =="Rosa") %>%
  as.data.frame()

#join data with inner_join (only matching observations are kept)
wildschwein_joined <- inner_join(wildschwein_Rosa,wildschwein_Sabi,by="roundToQuarterHour",suffix=c("Rosa","Sabi"))

#calculate distances + meet
wildschwein_distance <- wildschwein_joined %>%
  mutate(
    distance=euclid_dist(euclid_dist(ERosa,ESabi),euclid_dist(NRosa,NSabi)),
    meet=ifelse(distance<=100, TRUE, FALSE)
  )
head(wildschwein_distance)
```


```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
